name: LIFF Tests
on:
  pull_request:
  workflow_dispatch:

env:
  LIFF_URL: ${{ secrets.LIFF_URL }}
  LIFF_ID: ${{ secrets.LIFF_ID }}
  LIFF_PW: ${{ secrets.LIFF_PW }}
defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  LINE_Login:
    name: Job Liff Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      # - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py
      # - run: pip install wheel setuptools
      - name: Checking environment
        run: python --version
      - name: Setup selenium
        run: |
          pip install selenium
          pip install toml
          pip install chromedriver-binary
      - name: execute webdriver
        run: |
          python main.py --url $LIFF_URL --id $LIFF_ID --pw $LIFF_PW --headless --gha
      - name: show log
        run: cat my_liff.log
      - name: save log
        uses: actions/upload-artifact@v2
        with:
          name: selenium-log
          path: ./my_liff.log
