name: LIFF
on:
  pull_request:
  workflow_dispatch:

env:
  LIFF_URL: ${{ secrets.LIFF_URL }}
defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  helloWorld:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py
      - run: pip install wheel setuptools
      - name: Checking environment
        run: python --version
      - name: Setup selenium
        run: |
          pip install selenium
          pip install toml
          pip install chromedriver-binary
          # pip install chromedriver-binary==80.0.3987.106
      - name: test python
        run: |
          echo $(apt list --installed google*)
          python LiffTest.py $LIFF_URL $LIFF_ID $LIFF_PW
